import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import MenuBar, { MenuFrom } from '../../../../components/MenuBar/MenuBar'
const inter = Inter({ subsets: ['latin'] })
const YouBikeMenu: MenuFrom[] = [
    {
        MenuUrl: 'About',
        titleText: '使用說明'
    },
    {
        MenuUrl: 'Price',
        titleText: '收費方式'
    },
    {
        MenuUrl: 'StopInfo',
        titleText: '站點資訊'
    },
    {
        MenuUrl: 'News',
        titleText: '最新消息'
    },
    {
        MenuUrl: 'Event',
        titleText: '活動專區'
    },
]
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <body className={inter.className}>
                <MenuBar title={YouBikeMenu} currentPage="News" />
                {children}</body>
        </>
    )
}